/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as RecipientWishlistRouteImport } from './routes/recipient-wishlist'
import { Route as IndexRouteImport } from './routes/index'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinRoute = SpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipientWishlistRoute = RecipientWishlistRouteImport.update({
  id: '/recipient-wishlist',
  path: '/recipient-wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipient-wishlist': typeof RecipientWishlistRoute
  '/spin': typeof SpinRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipient-wishlist': typeof RecipientWishlistRoute
  '/spin': typeof SpinRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipient-wishlist': typeof RecipientWishlistRoute
  '/spin': typeof SpinRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipient-wishlist' | '/spin' | '/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipient-wishlist' | '/spin' | '/wishlist'
  id: '__root__' | '/' | '/recipient-wishlist' | '/spin' | '/wishlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipientWishlistRoute: typeof RecipientWishlistRoute
  SpinRoute: typeof SpinRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin': {
      id: '/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof SpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipient-wishlist': {
      id: '/recipient-wishlist'
      path: '/recipient-wishlist'
      fullPath: '/recipient-wishlist'
      preLoaderRoute: typeof RecipientWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipientWishlistRoute: RecipientWishlistRoute,
  SpinRoute: SpinRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
