/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgotPassword'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedWishlistRouteImport } from './routes/_authed.wishlist'
import { Route as AuthedSpinRouteImport } from './routes/_authed.spin'
import { Route as AuthedRecipientWishlistRouteImport } from './routes/_authed.recipient-wishlist'
import { Route as AuthedGiftGivingGuideRouteImport } from './routes/_authed.gift-giving-guide'
import { Route as AuthedFeedbackRouteImport } from './routes/_authed.feedback'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWishlistRoute = AuthedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSpinRoute = AuthedSpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipientWishlistRoute = AuthedRecipientWishlistRouteImport.update({
  id: '/recipient-wishlist',
  path: '/recipient-wishlist',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGiftGivingGuideRoute = AuthedGiftGivingGuideRouteImport.update({
  id: '/gift-giving-guide',
  path: '/gift-giving-guide',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFeedbackRoute = AuthedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/feedback': typeof AuthedFeedbackRoute
  '/gift-giving-guide': typeof AuthedGiftGivingGuideRoute
  '/recipient-wishlist': typeof AuthedRecipientWishlistRoute
  '/spin': typeof AuthedSpinRoute
  '/wishlist': typeof AuthedWishlistRoute
}
export interface FileRoutesByTo {
  '/forgotPassword': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/feedback': typeof AuthedFeedbackRoute
  '/gift-giving-guide': typeof AuthedGiftGivingGuideRoute
  '/recipient-wishlist': typeof AuthedRecipientWishlistRoute
  '/spin': typeof AuthedSpinRoute
  '/wishlist': typeof AuthedWishlistRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/forgotPassword': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/feedback': typeof AuthedFeedbackRoute
  '/_authed/gift-giving-guide': typeof AuthedGiftGivingGuideRoute
  '/_authed/recipient-wishlist': typeof AuthedRecipientWishlistRoute
  '/_authed/spin': typeof AuthedSpinRoute
  '/_authed/wishlist': typeof AuthedWishlistRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgotPassword'
    | '/login'
    | '/register'
    | '/feedback'
    | '/gift-giving-guide'
    | '/recipient-wishlist'
    | '/spin'
    | '/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgotPassword'
    | '/login'
    | '/register'
    | '/feedback'
    | '/gift-giving-guide'
    | '/recipient-wishlist'
    | '/spin'
    | '/wishlist'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/forgotPassword'
    | '/login'
    | '/register'
    | '/_authed/feedback'
    | '/_authed/gift-giving-guide'
    | '/_authed/recipient-wishlist'
    | '/_authed/spin'
    | '/_authed/wishlist'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotPassword': {
      id: '/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/wishlist': {
      id: '/_authed/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthedWishlistRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/spin': {
      id: '/_authed/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof AuthedSpinRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipient-wishlist': {
      id: '/_authed/recipient-wishlist'
      path: '/recipient-wishlist'
      fullPath: '/recipient-wishlist'
      preLoaderRoute: typeof AuthedRecipientWishlistRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/gift-giving-guide': {
      id: '/_authed/gift-giving-guide'
      path: '/gift-giving-guide'
      fullPath: '/gift-giving-guide'
      preLoaderRoute: typeof AuthedGiftGivingGuideRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/feedback': {
      id: '/_authed/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthedFeedbackRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedFeedbackRoute: typeof AuthedFeedbackRoute
  AuthedGiftGivingGuideRoute: typeof AuthedGiftGivingGuideRoute
  AuthedRecipientWishlistRoute: typeof AuthedRecipientWishlistRoute
  AuthedSpinRoute: typeof AuthedSpinRoute
  AuthedWishlistRoute: typeof AuthedWishlistRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedFeedbackRoute: AuthedFeedbackRoute,
  AuthedGiftGivingGuideRoute: AuthedGiftGivingGuideRoute,
  AuthedRecipientWishlistRoute: AuthedRecipientWishlistRoute,
  AuthedSpinRoute: AuthedSpinRoute,
  AuthedWishlistRoute: AuthedWishlistRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
